name: Additional job
on: [push]
jobs:
  wersja-docker-python:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: docker -v


  pylint-tester:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt install python3-flask
      - run: pip install pylint
      - run: pylint app.py
  uruchom-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install docker
      - run: docker build --tag test-flask-app .
      - run: docker run -d -p 5000:5000 test-flask-app 
